### ISSUE TITLE
Loader should ignore non-files in modules directory

### ISSUE THREAD

**Issue by levynir** [ForestAdmin/forest-express#106]
Non-files in the modules (directories esp.) cause the system to crash with the following error message:

```
[forest] 🌳🌳🌳  Cannot read your model in the file DIRNAME for the following reason: 
Error: Cannot find module '/PATH/TO/MODELS/DIRNAME'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /PATH/TO/node_modules/forest-express/index.js:28:11
```
Steps to reproduce:
create a sub-directory in your modules directory and try to re-load

**Comment by arnaudbesnier** [comment]
Thank you for the report!
The fix will be released today.

🌲🌲🌲
