### ISSUE TITLE
Cannot use async/await notation in models

### ISSUE THREAD

**Issue by lpatoyst** [ForestAdmin/forest-express#110]
Hi, 

We are currently unable to use async/await notation with sequelize/express. It is misleading and time consuming to investigate on such issues. We would like to be able to write models not syntactically analyzed by sequelize/express on pure node javascript.

```
> node -v; node ./bin/www

v8.4.0
Listening on port 3000
Open your admin UI: http://app.forestadmin.com
[forest] 🌳🌳🌳  Forest customization failed due to a syntax error: Unexpected token function in /home/lpayet/WebstormProjects/admin/forest/premium_subscription.js:16
[forest] 🌳🌳🌳  An error occured while computing the Forest apimap. Your application apimap cannot be sent to Forest. Your Admin UI might not reflect your application models.
Error
    at /home/lpayet/WebstormProjects/admin/node_modules/forest-express/index.js:156:23
    at tryCatcher (/home/lpayet/WebstormProjects/admin/node_modules/forest-express/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/lpayet/WebstormProjects/admin/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/lpayet/WebstormProjects/admin/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromiseCtx (/home/lpayet/WebstormProjects/admin/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:597:10)
    at Async._drainQueue (/home/lpayet/WebstormProjects/admin/node_modules/forest-express/node_modules/bluebird/js/release/async.js:131:12)
    at Async._drainQueues (/home/lpayet/WebstormProjects/admin/node_modules/forest-express/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues (/home/lpayet/WebstormProjects/admin/node_modules/forest-express/node_modules/bluebird/js/release/async.js:16:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by arnaudbesnier** [comment]
Hi @lpatoyst,

Thanks for the feedback!

This error seems to happen while inspecting the Forest customisation code (ie files in `/forest` directory). We need to be more permissive to let you use the ES2017 features.
We'll try to fix this next week.

About your ORM models, they can be written the way you like as the syntax is not inspected by Forest.

**Comment by arnaudbesnier** [comment]
@lpatoyst,
The fix is now available on the latest liana versions.

🌲🌲🌲
