### ISSUE TITLE
Upload file through API

### ISSUE THREAD

**Issue by XavierColombel** [ForestAdmin/forest-express#370]
## Expected behavior

I'm trying to upload files to server. **I've updated the Maximum Files Size parameter in my Fields configuration.** Is there a way to upload a larger file than 100kb, get it through the API, send it to AWS, then get the infos about upload and update collection? I didn't find any documentation about that.

## Actual behavior

 It seems the size limit is set to less than 100kb and every file is sent as a Base64. 

## Failure Logs

```
PUT /forest/leads/5e8b0e24cdd94010c9c66f12 413 4076 - 3.442 ms
PayloadTooLargeError: request entity too large
    at readStream (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/raw-body/index.js:155:17)
    at getRawBody (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/raw-body/index.js:108:12)
    at read (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/body-parser/lib/types/json.js:135:5)
    at Layer.handle [as handle_request] (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:317:13)
    at /Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:275:10)
    at logger (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/morgan/index.js:144:5)
    at Layer.handle [as handle_request] (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:317:13)
    at /Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:317:13)
    at /Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:275:10)
    at query (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:317:13)
    at /Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/sylvainartuys/Github/LessIsMore/my-admin/node_modules/express/lib/router/index.js:174:3)
```

## Context

I run API with Mongoose.
I've also set the file size limit to 10Mb 

```js
app.use(bodyParser.urlencoded({ limit: "10mb", extended: false }));
```

**Comment by XavierColombel** [comment]
I've found how to fix that. I made a mistake setting limit to `urlencoded`, I had to set it to `json`

```js
app.use(bodyParser.json({ limit: "10mb" }));
app.use(bodyParser.urlencoded({ extended: false }));
```

Then now I get the base64-encoded binary data I can transform in a real file and send it to server. 🎉
